version: '3.9'

services:
  go-app:
    container_name: go-app
    image: go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go-db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - 8000:8000
    depends_on:
      - go-db

  go-db:
    container_name: go-db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}